org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2,TLSv1.3
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.daemon=true
android.useAndroidX=true
android.enableJetifier=true
kotlin.incremental=false
systemProp.https.protocols=TLSv1.2,TLSv1.3
