name: Build Flutter APK

on:
  # تقدر تضيف push لو حابب، لكن حالياً نخليه manual
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          
          flutter-version: '3.22.0'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

    

      - name: Build release APK with Gradle
        working-directory: android
        run: ./gradlew assembleRelease

      - name: List generated APKs
        run: ls -R android/app/build/outputs

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: mr_delivery_supervisor-apk
          path: android/app/build/outputs/apk/release/*.apk
